# ---- modules/autoscaling/variables
variable "ami" {}
variable "instance_type" {}
variable "private_sn" {}
variable "key_name" {}
variable "webserver_target_group_arn" {}
variable "launch_config_sg" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "force_delete" {}
variable "asg_name" {}
variable "health_check_grace_period" {}
variable "health_check_type" {}
variable "policy_type" {}
variable "predefined_metric_type" {}
#variable "user_data" {}
variable "adjustment_type" {}
variable "target_value" {}
variable "root_block_device_encrypted" {}
variable "root_block_device_del_term" {}
variable "root_block_device_volume_type" {}
variable "root_block_device_volume_size" {}
